config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  get '/get_access_token',     to: "copyrights#get_access_token"
  get '/instagram_api',        to: "copyrights#instagram_api"
  get '/transaction_details',  to: "copyrights#transaction_details"
  post '/add_transaction',     to: "copyrights#add_transaction"
  get '/pending_transactions', to: "copyrights#pending_transactions"
  devise_for :users
  resources :copyrights
  root to: "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/copyright.rb
class Copyright < ApplicationRecord
has_attached_file :image, styles: {medium: "600x600>", thumb: "300x300>"}
validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
belongs_to :user
has_one :instagram_user
end

app/controllers/copyrights_controller.rb
require 'net/http'
class CopyrightsController < ApplicationController
  before_action :set_copyright, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  include Devise::Controllers::Helpers
    helper_method :current_user

  include Devise::Controllers::Helpers

  helper_method :current_user

  # GET /copyrights
  # GET /copyrights.json
  def index
    @copyrights = Copyright.all
  end

  # GET /copyrights/1
  # GET /copyrights/1.json
  def show
  end

  # GET /copyrights/new
  def new
    @copyright = Copyright.new
  end

  # GET /copyrights/1/edit
  def edit
  end

  # POST /copyrights
  # POST /copyrights.json
  def create
    params[:copyright] = params
    params[:copyright][:tags] = Digest::SHA2.hexdigest(File.binread(params[:image].tempfile))
    unless Copyright.where(tags: params[:copyright][:tags]).any?
     @copyright = Copyright.new(copyright_params)
     respond_to do |format|
       if @copyright.save
         add_transaction(@copyright.tags)
         format.html { redirect_to copyrights_url, notice: 'Copyright was successfully created.' }
       else
         format.html { render :new }
         format.json { render json: @copyright.errors, status: :unprocessable_entity }
       end
     end
    else
      redirect_back fallback_location: "/copyrights", alert: "Image already exists"
    end
  end

  # PATCH/PUT /copyrights/1
  # PATCH/PUT /copyrights/1.json
  def update
    respond_to do |format|
      if @copyright.update(copyright_params)
        format.html { redirect_to @copyright, notice: 'Copyright was successfully updated.' }
        format.json { render :show, status: :ok, location: @copyright }
      else
        format.html { render :edit }
        format.json { render json: @copyright.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /copyrights/1
  # DELETE /copyrights/1.json
  def destroy
    @copyright.destroy
    respond_to do |format|
      format.html { redirect_to copyrights_url, notice: 'Copyright was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_access_token
    url = URI("http://53d79249.ngrok.io/authorize_user")

    http = Net::HTTP.new(url.host, url.port)

    request = Net::HTTP::Get.new(url)
    request["cache-control"] = 'no-cache'
    request["postman-token"] = '4bab54b3-a698-d1ac-d7b0-6c15d41cc7ca'

    response = http.request(request)
    puts response.read_body
    url2 = response.read_body
    url2.slice!('Found. Redirecting to ')
    url = URI("#{url2}")

    http = Net::HTTP.new(url.host, url.port)

    request = Net::HTTP::Get.new(url)
    request["cache-control"] = 'no-cache'
    request["postman-token"] = '4bab54b3-a698-d1ac-d7b0-6c15d41cc7ca'

    response = http.request(request)

    puts response.read_body
    InstagramUser.create(user_id: current_user.id, accesstoken: response)
    render body: nil
  end

  def instagram_api
    # binding.pry
    url = URI('http://53d79249.ngrok.io/instapictures')
    http = Net::HTTP.new(url.host, url.port)
    # http.use_ssl = true
    # http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Post.new(url, 'Content-Type' => 'application/json')
    # request["acc"] = Rails.application.secrets.mixpanel_api_token
    # request["content-type"] = 'application/x-www-form-urlencoded'
    request["cache-control"] = 'no-cache'
    request.body = {accesstoken: current_user.instagram_user.access_key}.to_json
    @response = JSON.parse(http.request(request).read_body)
    images = @response["data"]
    images.each do |image|
      puts image
      image_url = image["images"]["standard_resolution"]["url"]
      id        = image["caption"]["id"]
      source    = 'instagram'
      uploaded_date = Date.jd(image["caption"]["created_time"].to_i)
      puts image_url
      unless Copyright.find_by(uploaded_id: id).present?
        copyright = Copyright.create(uploaded_id: id, photo_url: image_url, user_id: current_user.id, source: source)
        add_transaction(copyright.tags)
      end
      # a.save
      # puts a.errors.messages
    end
    render body: nil
  end

  def transaction_details
    user_id = current_user.id
    url = URI("http://53d79249.ngrok.io/usertransactions?userid=debayan")

    http = Net::HTTP.new(url.host, url.port)

    request = Net::HTTP::Get.new(url)
    request["cache-control"] = 'no-cache'
    request["postman-token"] = '29e3a29f-1b84-bf0a-4406-965ac77bec39'

    response = http.request(request)
    response = JSON.parse(response.read_body)
    puts response
    render body: nil
  end

  def add_transaction(tags)
    url = URI("http://53d79249.ngrok.io/addtransaction")

    http = Net::HTTP.new(url.host, url.port)

    request = Net::HTTP::Post.new(url)
    request["content-type"] = 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW'
    request["cache-control"] = 'no-cache'
    request["postman-token"] = 'dfe3c0df-ee40-bffc-da1d-43e9ab813639'
    request.body = {name: current_user.email, media: tags}.to_json

    response = http.request(request)
    puts response.read_body
  end

  def pending_transactions
    url = URI("http://53d79249.ngrok.io/pendingtransactions")

    http = Net::HTTP.new(url.host, url.port)

    request = Net::HTTP::Get.new(url)
    request["cache-control"] = 'no-cache'
    request["postman-token"] = '54f186e1-b992-2dc9-e58f-22be4ed3b943'

    response = http.request(request)
    puts response.read_body
    response = JSON.parse(response.read_body)
    puts response
    @data = response
    
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_copyright
      @copyright = Copyright.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def copyright_params
      params.require(:copyright).permit(:name, :image, :user_id, :date, :type_of_file, :tags, :uploaded_date, :source)
    end
end

app/helpers/copyrights_helper.rb
module CopyrightsHelper
end

app/views/copyrights/_form.html.erb
<%= form_with(model: copyright, local: true) do |form| %>
  <% if copyright.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(copyright.errors.count, "error") %> prohibited this copyright from being saved:</h2>

      <ul>
      <% copyright.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :copyright_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :copyright_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/copyrights/edit.html.erb
<h1>Editing Copyright</h1>

<%= render 'form', copyright: @copyright %>

<%= link_to 'Show', @copyright %> |
<%= link_to 'Back', copyrights_path %>

app/views/copyrights/index.html.erb
<!-- form itself -->
<!-- <form id="test-form" class="white-popup-block mfp-hide"> -->
<%= form_for Copyright.new, as: :post, url: copyrights_path, method: "POST", html: {id: 'test-form', class: "white-popup-block mfp-hide"} do |f| %>
<div class="container">
  <div class="frame">
    <h1>Add Your Image</h1>
    <div ng-app="ng-app" ng-init="checked = false">

      <label for="username">Name</label>
      <!-- <input class="form-styling" type="text" name="username" placeholder="File name"/> -->
      <%= f.text_field :name, name: "name", id: "copyright_name", class: "form-styling", placeholder: "File name" %>
      <div class="file-upload">
        <button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Add Image</button>

        <div class="image-upload-wrap">
          <%= f.file_field :image, name: "image", id: "copyright_image", class: "file-upload-input", onchange: "readURL(this);", accept: "image/*" %>
          <!-- <input class="file-upload-input" type='file' onchange="readURL(this);" accept="image/*" /> -->
          <div class="drag-text">
            <h3>Drag and drop a file or select add Image</h3>
          </div>
        </div>
        <div class="file-upload-content">
          <img class="file-upload-image" src="#" alt="your image"/>
          <div class="image-title-wrap">
            <button type="button" onclick="removeUpload()" class="remove-image">Remove
              <span class="image-title">Uploaded Image</span></button>
          </div>
        </div>
      </div>
      <div class="btn-animate">
        <%= f.hidden_field :user_id, name: "user_id", value: current_user.id %>
        <%= f.hidden_field :uploaded_date, name: "uploaded_date", value: Date.today %>
        <%= f.hidden_field :type_of_file, name: "type_of_file", value: "image" %>
        <%= f.hidden_field :source, name: "source", value: "image" %>
        <%= f.submit "#markitmine" , :class => "btn-signin", :style => "background-color: #1059ff;" %>
      </div>
      <!-- </form> -->
    </div>
  </div>

</div>
<% end %>
<!-- </form> -->

<div class="timeline-container" id="timeline-1">
<div class="timeline-header">
  <h2 class="timeline-header__title">#markitmine</h2>
  <h3 class="timeline-header__subtitle">#markitmine and make it yours. :)</h3>
</div>

<!-- link that opens popup -->
<div class="add-photos">
  <a href="#test-form" class="popup-with-form"><%= image_tag("add.png", size:"40", alt: "Add your image", title: "Add your image") %></a>
</div>

<div class="timeline">
  <% @copyrights.where(user_id: [current_user.id]).order("id DESC").each do |copyright| %>
    <div class="timeline-item" data-text="<%= copyright.name %>">
      <div class="timeline__content" style="min-height: 180px;">
        <% if copyright.photo_url.present? %>
        <a href="<%= copyright.photo_url %>" class="image-link">
          <img class="timeline__img" src="<%= copyright.photo_url %>"/>
        </a>
        <% else %>
          <a href="<%= copyright.image.expiring_url %>" class="image-link">
            <img class="timeline__img" src="<%= copyright.image.expiring_url %>"/>
          </a>
        <% end %>
        <h2 class="timeline__content-title"><%= copyright.created_at %></h2>
      </div>
    </div>
  <% end %>
</div>
</div>

<script type="text/javascript">
(function ($) {
  $.fn.timeline = function () {
    var selectors = {
      id: $(this),
      item: $(this).find(".timeline-item"),
      activeClass: "timeline-item--active",
      img: ".timeline__img"
    };
    selectors.item.eq(0).addClass(selectors.activeClass);
    selectors.id.css("background-image", "url(" + selectors.item.first().find(selectors.img).attr("src") + ")");
    var itemLength = selectors.item.length;
    $(window).scroll(function () {
      var max,
        min;
      var pos = $(this).scrollTop();
      selectors.item.each(function (i) {
        min = $(this).offset().top - 180;
        max = $(this).height() + $(this).offset().top;
        var that = $(this);
        if (i == itemLength - 2 && pos > min + $(this).height() / 2) {
          selectors.item.removeClass(selectors.activeClass);
          selectors.id.css("background-image", "url(" + selectors.item.last().find(selectors.img).attr("src") + ")");
          selectors.item.last().addClass(selectors.activeClass);
        } else if (pos <= max - 40 && pos >= min) {
          selectors.id.css("background-image", "url(" + $(this).find(selectors.img).attr("src") + ")");
          selectors.item.removeClass(selectors.activeClass);
          $(this).addClass(selectors.activeClass);
        }
      });
    });
  };
})(jQuery);

$("#timeline-1").timeline();

(function () {

  // Initialize popup as usual
  $('.image-link').magnificPopup({
    type: 'image', mainClass: 'mfp-with-zoom', // this class is for CSS animation below
    zoom: {
      enabled: true, // By default it's false, so don't forget to enable it

      duration: 300, // duration of the effect, in milliseconds
      easing: 'ease-in-out', // CSS transition easing function

      // The "opener" function should return the element from which popup will be zoomed in and to which popup will be scaled down By defailt it looks for an image tag:
      opener: function (openerElement) {
        // openerElement is the element on which popup was initialized, in this case its <a> tag you don't need to add "opener" option if this code matches your needs, it's defailt one.
        return openerElement.is('img')
          ? openerElement
          : openerElement.find('img');
      }
    }

  });

  $('.popup-with-form').magnificPopup({
    type: 'inline', preloader: false, focus: '#name',
    removalDelay: 300,

    // Class that is added to popup wrapper and background
    // make it unique to apply your CSS animations just to this exact popup
    mainClass: 'mfp-fade',

    // When elemened is focused, some mobile browsers in some cases zoom in It looks not nice, so we disable it:
    callbacks: {
      beforeOpen: function () {
        if ($(window).width() < 700) {
          this.st.focus = false;
        } else {
          this.st.focus = '#name';
        }
      }
    }
  });
}());

function readURL(input) {
  if (input.files && input.files[0]) {

    var reader = new FileReader();

    reader.onload = function (e) {
      $('.image-upload-wrap').hide();

      $('.file-upload-image').attr('src', e.target.result);
      $('.file-upload-content').show();

      $('.image-title').html(input.files[0].name);
    };

    reader.readAsDataURL(input.files[0]);

  } else {
    removeUpload();
  }
}

function removeUpload() {
  $('.file-upload-input').replaceWith($('.file-upload-input').clone());
  $('.file-upload-content').hide();
  $('.image-upload-wrap').show();
}
$('.image-upload-wrap').bind('dragover', function () {
  $('.image-upload-wrap').addClass('image-dropping');
});
$('.image-upload-wrap').bind('dragleave', function () {
  $('.image-upload-wrap').removeClass('image-dropping');
});
</script>

app/views/copyrights/new.html.erb
<h1>New Copyright</h1>

<%= render 'form', copyright: @copyright %>

<%= link_to 'Back', copyrights_path %>

app/views/copyrights/pending_transactions.html.erb
<div class="container-fluid" style="padding-top: 80px; margin-left: 20px; margin-right: 20px;">
<div class="container">
<table border="1" width="100%">
  <thead>
    <tr>
      <th width="30%">ID</th>
      <th width="50%">Media</th>
      <th width="20%">fromAddress</th>
    </tr>
  </thead>
  <tbody>
    <% @data.each do |data| %>
     <tr>
       <td width="30%"><%= data["_id"].to_s %></td>
       <td width="50%"><%= data["media"].to_s %></td>
       <td width="20%"><%= data["fromAddress"].to_s %></td>
     </tr
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/copyrights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @copyright.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @copyright.image %>
</p>

<%= image_tag @copyright.image.expiring_url(:thumb) %>

<%= link_to 'Edit', edit_copyright_path(@copyright) %> |
<%= link_to 'Back', copyrights_path %>